### ISSUE TITLE
[8.x] Missing test coverage for WYSIWYG. Media button broken.

### ISSUE THREAD

**Issue by grasmash** [acquia/lightning#73]
The media button on the packaged WYSIWYG editor should be tested via a @javascript Behat test. The feature appears to be broken, but all tests are passing.

Error: `Dropzone is not defined`

Note that you can ship custom step definitions with the profile if required. See: http://behat-drupal-extension.readthedocs.org/en/3.1/subcontexts.html#discovering-subcontexts

This custom step definition may be helpful as a guide:
````php
<?php
 /**
   * Fills in WYSIWYG editor with specified id.
   *
   * @Given /^(?:|I )fill in "(?P<text>[^"]*)" in WYSIWYG editor "([^"]*)"$/
   */
    public function iFillInInWYSIWYGEditor($text, $css_selector)
    {
        try {
            $element = $this->getSession()->getPage()->find('css', $css_selector);
            $id = $element->getAttribute('id');
            $this->getSession()->switchToIFrame($id);
        } catch (Exception $e) {
            throw new \Exception(sprintf("No iframe with id '%s' found on the page '%s'.", $id, $this->getSession()
            ->getCurrentUrl()));
        }
        $this->getSession()
        ->executeScript("document.body.innerHTML = '<p>" . $text . "</p>'");
        $this->getSession()->switchToIFrame();
    }
````

**Comment by grasmash** [comment]
This may be due in part to `libraries` missing as a dependency in the .make file.

**Comment by phenaproxima** [comment]
Thanks for suggesting this! I have hacked on a bit.

Turns out it's not possible to test the WYSIWYG by acquiring the iframe, because CKEditor does not give its iframe a name attribute (required by Mink for switchToIFrame()) or a CSS ID. But what IS possible is to call CKEditor's JavaScript API directly ;-)

I have implemented this in 233e2d640147137cef639c80ac6a07a6ec7c6fd7, so we will be able to add a few tests around the WYSIWYG.

**Comment by phenaproxima** [comment]
Added a single, extremely basic test of the WYSIWYG in #74.

**Comment by balsama** [comment]
I don't see any errors with the latest dev build. @phenaproxima can (should?) we do anything else beyond what you added in #74 to ensure that functionality is tested?

**Comment by phenaproxima** [comment]
I don't think so -- #74 will ensure that the widget actually shows up, and that should cover this issue. I think it's time to close this one...

**Comment by grasmash** [comment]
@phenaproxima I'm still experiencing a bug with the media feature. The wysiwyg editor is present, but clicking the "star" button for media does nothing but generate a JS error.

In addition to the current Behat test, could you add one that clicks the media button and asserts that the expected modal box appears?

**Comment by phenaproxima** [comment]
@grasmash, such a test already exists. It's in tests/features/media/media_library.feature.

**Comment by grasmash** [comment]
It seems that the issue stems from Lightning's assumption that it is installed at /profiles/lightning, when in fact it may be installed somewhere else like /profiles/contrib/lightning. This assumption is made in the *.libraries.yml files, which specify the required js locations in the following fashion: `/profiles/lightning/libraries/backbone.collectionView/dist/backbone.collectionView.min.js`

Rather that defining these js and css files relative to the docroot, they should be relative to lightning. E.g., `libraries/backbone.collectionView/dist/backbone.collectionView.min.js`. This seems to match the suggested pattern used in examples here: https://www.drupal.org/developing/api/8/assets

**Comment by phenaproxima** [comment]
Oooh, that's a really good point. Let's open a new issue for that, though.

**Comment by grasmash** [comment]
Will do.
